<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/09/29 00:44:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mielycanela',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
